import avatar from 'assets/images/avatar.jpg';
import cover from 'assets/images/cover.webp';
import { Post } from './types';

export const mockPosts: Post[] = [
  {
    section: 'Technology',
    authorName: 'John Doe',
    authorAvatar: avatar,
    publicationDate: '2022-03-15',
    title: 'The Future of Artificial Intelligence',
    coverImage: cover,
    views: 1200,
    likes: 850,
    comments: 45,
    bookmarks: 120,
  },
  {
    section: 'Travel',
    authorName: 'Jane Smith',
    authorAvatar: avatar,
    publicationDate: '2022-03-10',
    title: 'Exploring Hidden Gems in Europe',
    coverImage: cover,
    views: 980,
    likes: 720,
    comments: 32,
    bookmarks: 90,
  },
  {
    section: 'Science',
    authorName: 'David Johnson',
    authorAvatar: avatar,
    publicationDate: '2022-03-05',
    title: 'The Wonders of Space Exploration',
    coverImage: cover,
    views: 1500,
    likes: 1100,
    comments: 75,
    bookmarks: 200,
  },
  {
    section: 'Food',
    authorName: 'Maria Rodriguez',
    authorAvatar: avatar,
    publicationDate: '2022-03-02',
    title: 'Delicious Recipes from Around the World',
    coverImage: cover,
    views: 800,
    likes: 500,
    comments: 28,
    bookmarks: 80,
  },
  {
    section: 'Fashion',
    authorName: 'Alex Turner',
    authorAvatar: avatar,
    publicationDate: '2022-02-28',
    title: 'Latest Trends for the Season',
    coverImage: cover,
    views: 1200,
    likes: 890,
    comments: 60,
    bookmarks: 150,
  },
  {
    section: 'Health',
    authorName: 'Emily White',
    authorAvatar: avatar,
    publicationDate: '2022-02-25',
    title: 'Tips for a Healthy Lifestyle',
    coverImage: cover,
    views: 1100,
    likes: 750,
    comments: 42,
    bookmarks: 110,
  },
  {
    section: 'Sports',
    authorName: 'Michael Johnson',
    authorAvatar: avatar,
    publicationDate: '2022-02-20',
    title: 'Exciting Moments in Sports History',
    coverImage: cover,
    views: 1300,
    likes: 920,
    comments: 55,
    bookmarks: 180,
  },
  {
    section: 'Music',
    authorName: 'Sophie Davis',
    authorAvatar: avatar,
    publicationDate: '2022-02-15',
    title: 'Discover New Music Releases',
    coverImage: cover,
    views: 950,
    likes: 680,
    comments: 38,
    bookmarks: 100,
  },
  {
    section: 'Movies',
    authorName: 'Robert Turner',
    authorAvatar: avatar,
    publicationDate: '2022-02-10',
    title: 'Must-Watch Films of the Year',
    coverImage: cover,
    views: 1050,
    likes: 800,
    comments: 48,
    bookmarks: 130,
  },
  {
    section: 'Art',
    authorName: 'Emma Parker',
    authorAvatar: avatar,
    publicationDate: '2022-02-05',
    title: 'Exploring Contemporary Art',
    coverImage: cover,
    views: 900,
    likes: 600,
    comments: 34,
    bookmarks: 95,
  },
  {
    section: 'Politics',
    authorName: 'Daniel Harris',
    authorAvatar: avatar,
    publicationDate: '2022-02-02',
    title: 'Current Political Landscape',
    coverImage: cover,
    views: 1100,
    likes: 780,
    comments: 50,
    bookmarks: 160,
  },
  {
    section: 'Nature',
    authorName: 'Olivia Turner',
    authorAvatar: avatar,
    publicationDate: '2022-01-28',
    title: 'Beautiful Landscapes Around the World',
    coverImage: cover,
    views: 1000,
    likes: 720,
    comments: 40,
    bookmarks: 120,
  },
  {
    section: 'Books',
    authorName: 'William Jackson',
    authorAvatar: avatar,
    publicationDate: '2022-01-25',
    title: 'Recommended Books for Every Reader',
    coverImage: cover,
    views: 850,
    likes: 550,
    comments: 30,
    bookmarks: 85,
  },
  {
    section: 'Business',
    authorName: 'Sophia Roberts',
    authorAvatar: avatar,
    publicationDate: '2022-01-20',
    title: 'Entrepreneurship and Business Tips',
    coverImage: cover,
    views: 1200,
    likes: 870,
    comments: 58,
    bookmarks: 140,
  },
  {
    section: 'Education',
    authorName: 'Ethan Walker',
    authorAvatar: avatar,
    publicationDate: '2022-01-15',
    title: 'Innovations in Education',
    coverImage: cover,
    views: 950,
    likes: 690,
    comments: 37,
    bookmarks: 105,
  },
];
